import type { ReactElement } from 'react';
import Base from '@/shared/layouts/base';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { NextPageWithLayout } from '@/shared/interfaces/base';

const Home: NextPageWithLayout = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />{' '}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="text-3xl text-rose-600"
        onClick={() => router.push('/example')}
      >
        Hello Geeks!
      </div>
    </>
  );
};

const getLayout = (page: ReactElement) => {
  return <Base>{page}</Base>;
};
Home.getLayout = getLayout;

export default Home;
